### ISSUE TITLE
Missing Gemfile on both branches

### ISSUE THREAD

**Issue by lantzbuilds** [learn-co-curriculum/phase-4-data-structures-implement-a-stack#2]
### Canvas Link

https://learning.flatironschool.com/courses/4995/assignments/173130?module_item_id=377946

### Concern

README doesn't mention running `bundle install` but students unable to run tests unless they have rspec installed globally.
Students unable to run `learn test` or `rspec` due to lack of Gemfile.

### Suggested Changes

Add Gemfile with `gem 'rspec'`  and also add instruction to README to run `bundle install`

**Comment by lizbur10** [comment]
Hi @betalantz ! We weren't able to recreate this issue, and I'm a little confused about it because none of the labs in this module have gemfiles. Has this problem come up anywhere else?

**Comment by lizbur10** [comment]
Hi again @betalantz! Since I'm not sure what's broken here, I'm going to go ahead and close this issue. If you can provide any additional info, please feel free to reopen it 💙
